#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; IMAGE="dokku/$APP"
echo "-----> Installing ffmpeg ..."
COMMAND=$(cat <<EOF
echo "-----> install requirements"

export DEBIAN_FRONTEND=noninteractive
sudo curl https://tuitu-buildpack.oss-cn-hangzhou.aliyuncs.com/sources.list -o /etc/apt/sources.list

apt-get -y update
apt-get install -y software-properties-common
apt-get install -y --reinstall ca-certificates
add-apt-repository -y ppa:kirillshkrogalev/ffmpeg-next
sh -c '
  set +e
  bash -e <<TRY
    apt-get -y update
    apt-get install -y ffmpeg
  TRY
  if [ $? -ne 0 ]; then
    apt-get install -y ffmpeg
  fi
'


sleep 1 # wait so that docker run has not exited before docker attach
EOF
)
id=$(docker run -d $IMAGE /bin/bash -e -c "$COMMAND")
#enable logs
docker attach $id
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
